### ISSUE TITLE
Fix broken link

### ISSUE THREAD

**Issue by EliasPereyra** [kenyipp/realworld-nodejs-example-app#1]
In the #arquitecture section, the blog post link mentioned doesn't work

**Comment by kenyipp** [comment]
Hi @EliasPereyra! 

The previous blog post is no longer available, but I just completed a refactoring and have rewritten the post here: [Crafting a Scalable Node.js API: Insights from My Real-World Project with Express, Knex, and AWS CDK](https://medium.com/@ken20206/crafting-a-scalable-node-js-api-insights-from-my-realworld-project-with-express-knex-and-aws-cdk-056523e70b69). 

Feel free to reach out if you have any questions. Thanks!

**Comment by EliasPereyra** [comment]
Awesome @kenyipp thank you for sharing your new post, I'll read it 👍🏼
